<?PHP
/**-------------- Copyright (C) 2013 - Mavericks Trynity -------------------------
    

     | ###      ###    ####  ##           ## ######### ########   ##  ###### ########
     | ## #    # ##  ##    ## ##         ##  ##        ##    ##   ##  ##     ##
     | ##  #  #  ##  ##    ##  ##       ##   ##        ########   ##  ##      ##
     | ##   ##   ##  ##    ##   ##     ##    ########  ##         ##  ##        ##
     | ##        ##  ########    ##   ##     ##        ###        ##  ##          ##
     | ##        ##  ##    ##     ## ##      ##        ##  ##     ##  ##           ##
     | ##        ##  ##    ##      ##        ######### ##     ##  ##  ###### #######

     * Author: |Lion (Kevin) - All rights reserved.
     * This program is private: you can not redistribute it and/or modify

   ----------------------------------------------------------------------*/

$Permission['HOUSEKEEPING']['MIN_RANK']      =    5;

$Permission['HOUSEKEEPING']['HOME']          =    5;
$Permission['HOUSEKEEPING']['SETTINGS_SERVR']=    7;
$Permission['HOUSEEKEPING']['USERS_BANS']    =    5;
$Permission['HOUSEKEEPING']['USERS_UNBAN']   =    6;
$Permission['HOUSEKEEPING']['ARTICLES_NEW']  =    6;
$Permission['HOUSEKEEPING']['ARTICLES_DEL']  =    7;
$Permission['HOUSEKEEPING']['SERVER_CMD']    =    9;
$Permission['HOUSEKEEPING']['STATICS']       =    9;
$Permission['HOUSEKEEPING']['HKLOGS']        =    9;  